name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-cloud-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialise Quant Cloud
        uses: ./
        env:
          SECTION_K8S_API_URL: "${{ secrets.SECTION_K8S_API_URL }}"
          SECTION_API_TOKEN: "${{ secrets.SECTION_API_TOKEN }}"
      - name: Check KUBECONFIG is set
        shell: bash
        run: exit 1
        if: env.KUBECONFIG == ''
      - name: Check Kubernetes connection
        run: kubectl get pods
        env:
          KUBECONFIG: '' # unset 